name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest

    name: run-precommit
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.3

      - uses: actions/setup-python@v2.1.3
        with:
          python-version: "3.x"

      - name: Get full python version
        id: full-python-version
        run: |
          echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")

      - name: install poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - name: poetry cache
        uses: actions/cache@v2.1.1
        with:
          path: .venv
          key: venv-${{ matrix.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: install dependencies
        run: poetry install

      - name: pre-commit cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.full-python-version.outputs.version }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: run pre-commit
        run: |
          poetry run  pre-commit run --all-files --show-diff-on-failure
